package xin.qicloud.vhr.bean;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.name
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.parentId
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.depPath
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private String deppath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.enabled
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.isParent
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Boolean isparent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.id
     *
     * @return the value of department.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.id
     *
     * @param id the value for department.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.name
     *
     * @return the value of department.name
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.name
     *
     * @param name the value for department.name
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.parentId
     *
     * @return the value of department.parentId
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.parentId
     *
     * @param parentid the value for department.parentId
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.depPath
     *
     * @return the value of department.depPath
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public String getDeppath() {
        return deppath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.depPath
     *
     * @param deppath the value for department.depPath
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setDeppath(String deppath) {
        this.deppath = deppath == null ? null : deppath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.enabled
     *
     * @return the value of department.enabled
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.enabled
     *
     * @param enabled the value for department.enabled
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.isParent
     *
     * @return the value of department.isParent
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Boolean getIsparent() {
        return isparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.isParent
     *
     * @param isparent the value for department.isParent
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setIsparent(Boolean isparent) {
        this.isparent = isparent;
    }
}