package xin.qicloud.vhr.bean;

import java.util.Date;

public class Employeeremove {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeremove.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeremove.eid
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeremove.afterDepId
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Integer afterdepid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeremove.afterJobId
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Integer afterjobid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeremove.removeDate
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Date removedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeremove.reason
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeremove.remark
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeremove.id
     *
     * @return the value of employeeremove.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeremove.id
     *
     * @param id the value for employeeremove.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeremove.eid
     *
     * @return the value of employeeremove.eid
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeremove.eid
     *
     * @param eid the value for employeeremove.eid
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeremove.afterDepId
     *
     * @return the value of employeeremove.afterDepId
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Integer getAfterdepid() {
        return afterdepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeremove.afterDepId
     *
     * @param afterdepid the value for employeeremove.afterDepId
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setAfterdepid(Integer afterdepid) {
        this.afterdepid = afterdepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeremove.afterJobId
     *
     * @return the value of employeeremove.afterJobId
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Integer getAfterjobid() {
        return afterjobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeremove.afterJobId
     *
     * @param afterjobid the value for employeeremove.afterJobId
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setAfterjobid(Integer afterjobid) {
        this.afterjobid = afterjobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeremove.removeDate
     *
     * @return the value of employeeremove.removeDate
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Date getRemovedate() {
        return removedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeremove.removeDate
     *
     * @param removedate the value for employeeremove.removeDate
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setRemovedate(Date removedate) {
        this.removedate = removedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeremove.reason
     *
     * @return the value of employeeremove.reason
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeremove.reason
     *
     * @param reason the value for employeeremove.reason
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeremove.remark
     *
     * @return the value of employeeremove.remark
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeremove.remark
     *
     * @param remark the value for employeeremove.remark
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}