package xin.qicloud.vhr.bean;

import java.util.Date;

public class Employeeec {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeec.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeec.eid
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeec.ecDate
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Date ecdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeec.ecReason
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private String ecreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeec.ecPoint
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Integer ecpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeec.ecType
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Integer ectype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employeeec.remark
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeec.id
     *
     * @return the value of employeeec.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeec.id
     *
     * @param id the value for employeeec.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeec.eid
     *
     * @return the value of employeeec.eid
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeec.eid
     *
     * @param eid the value for employeeec.eid
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeec.ecDate
     *
     * @return the value of employeeec.ecDate
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Date getEcdate() {
        return ecdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeec.ecDate
     *
     * @param ecdate the value for employeeec.ecDate
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setEcdate(Date ecdate) {
        this.ecdate = ecdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeec.ecReason
     *
     * @return the value of employeeec.ecReason
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public String getEcreason() {
        return ecreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeec.ecReason
     *
     * @param ecreason the value for employeeec.ecReason
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setEcreason(String ecreason) {
        this.ecreason = ecreason == null ? null : ecreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeec.ecPoint
     *
     * @return the value of employeeec.ecPoint
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Integer getEcpoint() {
        return ecpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeec.ecPoint
     *
     * @param ecpoint the value for employeeec.ecPoint
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setEcpoint(Integer ecpoint) {
        this.ecpoint = ecpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeec.ecType
     *
     * @return the value of employeeec.ecType
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Integer getEctype() {
        return ectype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeec.ecType
     *
     * @param ectype the value for employeeec.ecType
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setEctype(Integer ectype) {
        this.ectype = ectype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employeeec.remark
     *
     * @return the value of employeeec.remark
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employeeec.remark
     *
     * @param remark the value for employeeec.remark
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}