package xin.qicloud.vhr.bean;

public class HrRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_role.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_role.hrid
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Integer hrid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_role.rid
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Integer rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_role.id
     *
     * @return the value of hr_role.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_role.id
     *
     * @param id the value for hr_role.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_role.hrid
     *
     * @return the value of hr_role.hrid
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Integer getHrid() {
        return hrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_role.hrid
     *
     * @param hrid the value for hr_role.hrid
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setHrid(Integer hrid) {
        this.hrid = hrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_role.rid
     *
     * @return the value of hr_role.rid
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_role.rid
     *
     * @param rid the value for hr_role.rid
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}