package xin.qicloud.vhr.bean;

import java.util.Date;

public class Joblevel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joblevel.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joblevel.name
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joblevel.titleLevel
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private String titlelevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joblevel.createDate
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joblevel.enabled
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Boolean enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joblevel.id
     *
     * @return the value of joblevel.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joblevel.id
     *
     * @param id the value for joblevel.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joblevel.name
     *
     * @return the value of joblevel.name
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joblevel.name
     *
     * @param name the value for joblevel.name
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joblevel.titleLevel
     *
     * @return the value of joblevel.titleLevel
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public String getTitlelevel() {
        return titlelevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joblevel.titleLevel
     *
     * @param titlelevel the value for joblevel.titleLevel
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setTitlelevel(String titlelevel) {
        this.titlelevel = titlelevel == null ? null : titlelevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joblevel.createDate
     *
     * @return the value of joblevel.createDate
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joblevel.createDate
     *
     * @param createdate the value for joblevel.createDate
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joblevel.enabled
     *
     * @return the value of joblevel.enabled
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joblevel.enabled
     *
     * @param enabled the value for joblevel.enabled
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}