package xin.qicloud.vhr.bean;

public class MenuRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_role.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_role.mid
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_role.rid
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Integer rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_role.id
     *
     * @return the value of menu_role.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_role.id
     *
     * @param id the value for menu_role.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_role.mid
     *
     * @return the value of menu_role.mid
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_role.mid
     *
     * @param mid the value for menu_role.mid
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_role.rid
     *
     * @return the value of menu_role.rid
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_role.rid
     *
     * @param rid the value for menu_role.rid
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}