package xin.qicloud.vhr.bean;

public class Politicsstatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column politicsstatus.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column politicsstatus.name
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column politicsstatus.id
     *
     * @return the value of politicsstatus.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column politicsstatus.id
     *
     * @param id the value for politicsstatus.id
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column politicsstatus.name
     *
     * @return the value of politicsstatus.name
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column politicsstatus.name
     *
     * @param name the value for politicsstatus.name
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}