package xin.qicloud.vhr.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import xin.qicloud.vhr.bean.Adjustsalary;
import xin.qicloud.vhr.bean.AdjustsalaryExample;

public interface AdjustsalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    long countByExample(AdjustsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int deleteByExample(AdjustsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int insert(Adjustsalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int insertSelective(Adjustsalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    List<Adjustsalary> selectByExample(AdjustsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    Adjustsalary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") Adjustsalary record, @Param("example") AdjustsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByExample(@Param("record") Adjustsalary record, @Param("example") AdjustsalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByPrimaryKeySelective(Adjustsalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByPrimaryKey(Adjustsalary record);
}