package xin.qicloud.vhr.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import xin.qicloud.vhr.bean.Appraise;
import xin.qicloud.vhr.bean.AppraiseExample;

public interface AppraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    long countByExample(AppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int deleteByExample(AppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int insert(Appraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int insertSelective(Appraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    List<Appraise> selectByExample(AppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    Appraise selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") Appraise record, @Param("example") AppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByExample(@Param("record") Appraise record, @Param("example") AppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByPrimaryKeySelective(Appraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByPrimaryKey(Appraise record);
}