package xin.qicloud.vhr.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import xin.qicloud.vhr.bean.HrRole;
import xin.qicloud.vhr.bean.HrRoleExample;

public interface HrRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    long countByExample(HrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int deleteByExample(HrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int insert(HrRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int insertSelective(HrRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    List<HrRole> selectByExample(HrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    HrRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") HrRole record, @Param("example") HrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByExample(@Param("record") HrRole record, @Param("example") HrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByPrimaryKeySelective(HrRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByPrimaryKey(HrRole record);
}