package xin.qicloud.vhr.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import xin.qicloud.vhr.bean.Joblevel;
import xin.qicloud.vhr.bean.JoblevelExample;

public interface JoblevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblevel
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    long countByExample(JoblevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblevel
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int deleteByExample(JoblevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblevel
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblevel
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int insert(Joblevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblevel
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int insertSelective(Joblevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblevel
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    List<Joblevel> selectByExample(JoblevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblevel
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    Joblevel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblevel
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") Joblevel record, @Param("example") JoblevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblevel
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByExample(@Param("record") Joblevel record, @Param("example") JoblevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblevel
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByPrimaryKeySelective(Joblevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblevel
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByPrimaryKey(Joblevel record);
}