package xin.qicloud.vhr.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import xin.qicloud.vhr.bean.Msgcontent;
import xin.qicloud.vhr.bean.MsgcontentExample;

public interface MsgcontentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    long countByExample(MsgcontentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int deleteByExample(MsgcontentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int insert(Msgcontent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int insertSelective(Msgcontent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    List<Msgcontent> selectByExample(MsgcontentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    Msgcontent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") Msgcontent record, @Param("example") MsgcontentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByExample(@Param("record") Msgcontent record, @Param("example") MsgcontentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByPrimaryKeySelective(Msgcontent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated Tue Aug 27 19:29:39 CST 2019
     */
    int updateByPrimaryKey(Msgcontent record);
}